files:
  - source: /ui/localization.csv
    translation: /ui/%two_letters_code%.%file_extension%
    multilingual_spreadsheet: 1
    first_line_contains_header: 1
    scheme: 'identifier,source_phrase,de,fr'
  - source: /mods/*/localization.csv
    translation: /%original_path%/%two_letters_code%.%file_extension%
    multilingual_spreadsheet: 1
    first_line_contains_header: 1
    scheme: 'identifier,source_phrase,de'
