blank_issues_enabled: false
contact_links:
  - name: Discord Community Server
    url: https://discord.linwood.tk/
    about: Please talk here.
  - name: GitHub Discussions
    url: https://github.com/LinwoodCloud/world/discussions
    about: Please ask and answer questions here.
